# Author(s): Studios TKOH!
# Year: 2025

spring.application.name=gestor-cliente

# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false

# API REST Externa
integration.decolecta.token=${DECOLECTA_TOKEN}
integration.decolecta.ruc-url=${DECOLECTA_RUC_URL}
integration.decolecta.dni-url=${DECOLECTA_DNI_URL}
